[package]
name = "stella"
version = "0.1.0"
edition = "2024"

[dependencies]
slint = { version = "1.13.1", default-features = false, features = [
	"backend-winit",
	"compat-1-2",
	"std",
	"renderer-software",
] }

[build-dependencies]
slint-build = "1.13.1"
